name: 'A11Y-Checker'
description: 'Github Action for checking PRs against accessibility guidelines and provide suggested fixes as comments, using agents'
author: 'Pablo Schaffner <pablo@puntorigen.com>'
inputs:
  github-token:
    description: 'GitHub Token to authenticate the action.'
    required: true
    default: ${{ github.token }}
  openai-api-key:
    description: 'OpenAI API Key to use the GPT-4 model.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.openai-api-key }}
branding:
  icon: 'git-pull-request'
  color: 'blue'
